// Regenerates src/lib/icons.js from Simple Icons (CC0-1.0, no attribution
// required — credited anyway in the generated file).
//
// Icons are inlined as SVG path data rather than <img> tags on purpose:
// GitHub's Content-Security-Policy restricts img-src to data:, blob: and its
// own hosts, so a remote icon URL would simply not render. Inline <svg> is not
// subject to img-src at all, needs no network at display time, and inherits
// currentColor so one path works in both themes.

import { writeFileSync } from 'node:fs';

// slug -> the extensions it should stand for.
const WANTED = {
  python: ['py', 'pyi', 'pyx'],
  markdown: ['md', 'markdown', 'mdx'],
  javascript: ['js', 'mjs', 'cjs'],
  typescript: ['ts', 'mts', 'cts'],
  react: ['jsx', 'tsx'],
  rust: ['rs'],
  go: ['go'],
  ruby: ['rb', 'gemfile'],
  php: ['php'],
  json: ['json', 'jsonc'],
  yaml: ['yaml', 'yml'],
  toml: ['toml'],
  html5: ['html', 'htm'],
  css: ['css'],
  sass: ['scss', 'sass'],
  gnubash: ['sh', 'bash', 'zsh', 'fish'],
  docker: ['dockerfile'],
  terraform: ['tf', 'tfvars'],
  graphql: ['graphql', 'gql'],
  svg: ['svg'],
  lua: ['lua'],
  swift: ['swift'],
  kotlin: ['kt', 'kts'],
  c: ['c', 'h'],
  cplusplus: ['cpp', 'cxx', 'cc', 'hpp'],
  dotnet: ['cs', 'csproj', 'fs'],
  elixir: ['ex', 'exs'],
  haskell: ['hs'],
  zig: ['zig'],
  scala: ['scala'],
  perl: ['pl', 'pm'],
  r: ['r'],
  julia: ['jl'],
  ocaml: ['ml', 'mli'],
  nixos: ['nix'],
  gnumake: ['makefile', 'mk'],
  git: ['.gitignore', '.gitattributes', '.gitmodules'],
};

const BASE = 'https://cdn.jsdelivr.net/npm/simple-icons@15/icons';

async function fetchIcon(slug) {
  const res = await fetch(`${BASE}/${slug}.svg`);
  if (!res.ok) return null;
  const svg = await res.text();
  const path = /\sd="([^"]+)"/.exec(svg);
  return path ? path[1] : null;
}

async function fetchMeta() {
  const res = await fetch('https://cdn.jsdelivr.net/npm/simple-icons@15/data/simple-icons.json');
  if (!res.ok) return {};
  const data = await res.json();
  const list = Array.isArray(data) ? data : data.icons ?? [];
  const bySlug = {};
  for (const icon of list) {
    const slug = (icon.slug ?? icon.title ?? '').toLowerCase().replace(/[^a-z0-9]/g, '');
    if (slug) bySlug[slug] = icon.hex;
  }
  return bySlug;
}

// Brand colors are chosen for a brand's own backdrop, not GitHub's. Several
// (markdown, rust) are pure black and vanish on a dark theme. Clamp each one
// toward the background until it clears 3:1, the WCAG threshold for graphics,
// and emit a variant per theme.
const LIGHT_BG = [255, 255, 255];
const DARK_BG = [13, 17, 23]; // GitHub dark --bgColor-default

const toRgb = (hex) => [1, 3, 5].map((i) => parseInt(hex.slice(i, i + 2), 16));
const toHex = (rgb) => '#' + rgb.map((c) => Math.round(c).toString(16).padStart(2, '0')).join('');

function luminance([r, g, b]) {
  const f = (c) => {
    const s = c / 255;
    return s <= 0.03928 ? s / 12.92 : ((s + 0.055) / 1.055) ** 2.4;
  };
  return 0.2126 * f(r) + 0.7152 * f(g) + 0.0722 * f(b);
}

function contrast(a, b) {
  const [hi, lo] = [luminance(a), luminance(b)].sort((x, y) => y - x);
  return (hi + 0.05) / (lo + 0.05);
}

const mix = (a, b, t) => a.map((c, i) => c + (b[i] - c) * t);

function clampToBackground(hex, bg) {
  const brand = toRgb(hex);
  if (contrast(brand, bg) >= 3) return toHex(brand);
  // Move away from the background: toward white on dark, toward black on light.
  const target = luminance(bg) > 0.5 ? [0, 0, 0] : [255, 255, 255];
  for (let t = 0.05; t <= 1; t += 0.05) {
    const candidate = mix(brand, target, t);
    if (contrast(candidate, bg) >= 3) return toHex(candidate);
  }
  return toHex(target);
}

const meta = await fetchMeta();
const paths = {};
const extToIcon = {};
const colors = {};
const missing = [];

for (const [slug, extensions] of Object.entries(WANTED)) {
  const path = await fetchIcon(slug);
  if (!path) { missing.push(slug); continue; }
  paths[slug] = path;
  const brand = meta[slug] ? `#${meta[slug]}` : null;
  colors[slug] = brand
    ? { light: clampToBackground(brand, LIGHT_BG), dark: clampToBackground(brand, DARK_BG) }
    : null;
  for (const ext of extensions) extToIcon[ext] = slug;
}

const body = `// GENERATED by tools/fetch-icons.mjs — do not edit by hand.
//
// Icon paths from Simple Icons (https://simpleicons.org), CC0-1.0.
// Inlined as <svg> path data rather than <img>: GitHub's CSP limits img-src to
// data:, blob: and its own hosts, so remote icon URLs cannot render, and inline
// SVG inherits currentColor so one path serves both themes.

/** Icon slug -> SVG path data, drawn on a 24x24 viewBox. */
export const ICON_PATHS = ${JSON.stringify(paths, null, 2)};

/** Icon slug -> {light, dark} brand color, contrast-clamped per theme. */
export const ICON_COLORS = ${JSON.stringify(colors, null, 2)};

/** Lower-cased file extension (or whole basename) -> icon slug. */
export const EXTENSION_ICONS = ${JSON.stringify(extToIcon, null, 2)};

export function iconForExtension(ext) {
  return EXTENSION_ICONS[String(ext).toLowerCase()] ?? null;
}
`;

writeFileSync(new URL('../src/lib/icons.js', import.meta.url), body);
const bytes = Buffer.byteLength(body);
console.log(`src/lib/icons.js — ${Object.keys(paths).length} icons, ${Object.keys(extToIcon).length} extensions, ${(bytes / 1024).toFixed(1)} KB`);
if (missing.length) console.log('missing slugs (skipped):', missing.join(', '));
